services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: indexer
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"