[package]
name = "db"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
publish.workspace = true

[dependencies]
refinery = { workspace = true }
tokio = { workspace = true }
sqlx = { workspace = true }
dotenv = {workspace = true}
